let data = [
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Fancy Product',
    priceRange: true,
    startPrice: 40,
    endPrice: 80,
    listPrice: null,
    price: null,
    sale: false,
    rating: null,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Special Product',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: 20,
    price: 18,
    sale: true,
    rating: null,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Sale Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: 50,
    price: 25,
    sale: true,
    rating: 3.7,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Popular Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: null,
    price: 40,
    sale: false,
    rating: 5,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Sale Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: 50,
    price: 25,
    sale: true,
    rating: null,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Fancy Product',
    priceRange: true,
    startPrice: 120,
    endPrice: 280,
    listPrice: null,
    price: null,
    sale: false,
    rating: null,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Special Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: 20,
    price: 18,
    sale: true,
    rating: 5,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Popular Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: null,
    price: 40,
    sale: false,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Sale Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: 50,
    price: 25,
    sale: true,
    rating: 4.6,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Popular Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: null,
    price: 40,
    sale: false,
    rating: 5,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Sale Item',
    priceRange: false,
    startPrice: null,
    endPrice: null,
    listPrice: 50,
    price: 25,
    sale: true,
    rating: 3.5,
  },
  {
    image: 'https://dummyimage.com/450x300/dee2e6/6c757d.jpg',
    title: 'Fancy Product',
    priceRange: true,
    startPrice: 120,
    endPrice: 280,
    listPrice: null,
    price: null,
    sale: false,
    rating: null,
  },
];

export default data;
